### ISSUE TITLE
tmpfile missing from repo

### ISSUE THREAD

**Issue by ghost** [gwolfis/f5-atc-workshop#1]
I'm attempting to build the environment from my local machine but when I run `terraform plan` I can see that the `tmpfile` is expected to be outside the root directory of the repo in `../files/tmp.yml`.  An example of the contents of tmpfile should be located in the root of the repo similar to the way you are doing the `setup.yml` and the docs need to be updated to reflect that you need to copy `tmp-changeme.yml` to `tmp.yml` and then to make the necessary edits.

**Comment by gwolfis** [comment]
The getting started section and module 1 explains how to setup the environment. The JSON environment file will get generated automatically from the Terraform dynamic delivered values. This file will get published in /postman, but let me clarify this a bit more.

**Comment by gwolfis** [comment]
I added a "how things work" paragraph in the "Getting Started" section.

**Comment by gwolfis** [comment]
New sections have been added to the labguide and now include a track for non UDF users and UDF users and new sections have been added to guide how to obtain and install global Postman variables. Please give it a try and let me know.

**Comment by ghost** [comment]
Great addition @gwolfis! I've only tested the non-UDF instructions so far. One small suggestion. When I go down the path of installing without UDF I get to this page:

https://github.com/gwolfis/f5-atc-workshop/blob/master/docs/module_1/task1_0.md

The NEXT button takes you the beginning steps of using UDF. I think you should update that link to jump to Step 13 or maybe split that page into 2 separate pages and put the content from Step 13 to the end into the second page. Then when you click next on both the UDF and non-UDF page you end up with the same content. I think this will be less confusing for the non-UDF users.

**Comment by gwolfis** [comment]
Non-UDF users and UDF users have separate session now which explains how to prep from top to bottom. Task1.0 does this for non-UDF users and task1.1 guides UDF users. Clicking 'Next' at both pages will move you into preparing Postman.

**Comment by ghost** [comment]
Nice work! that was a perfect solution.

**Comment by gwolfis** [comment]
Thanks Victor. Do you agree that the issue can be closed.

Excuse my errors, this message was sent from a mobile device.

________________________________
Van: Victor Granic <notifications@github.com>
Verzonden: Friday, October 30, 2020 5:44:29 PM
Aan: gwolfis/f5-atc-workshop <f5-atc-workshop@noreply.github.com>
CC: Gert Wolfis <G.Wolfis@F5.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [gwolfis/f5-atc-workshop] tmpfile missing from repo (#1)


EXTERNAL MAIL: noreply@github.com


Nice work! that was a perfect solution.

**Comment by ghost** [comment]
Yes, Gert!
